title: StyLivJek
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  StyLivJek, a jekyll configuration
baseurl: "/ventureretreat" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - hawkins
  - jekyll-babel
  - jekyll-minifier

stylus:
  compress: true
  path: css

# page_gen:
#   - index_files: true
#     data: 'events'
#     template: 'event'
#     name: 'title'
#     dir: 'event'

jekyll_admin:
  hidden_links:
    - configuration

# Exclude from processing.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - script
  - rakefile

defaults:
  - scope:
      path: "events"
      type: "posts"
    values:
      tags: ["event"]
      layout: "event"
      permalink: "/event/:title"
      location: "Insert this location location"
      image: "1.png"
      when_header: "September 14-17, 2018"
      caratteristics:
        altitude: "2240 mt"
        cooking: "Traditional"
        beds: "70 peope"
      past_edition:
        date: "14 - 15 - 16 - 17 February 2018"
        pic: "oberholz_refuge.png"
      speakers:
      - name: "Tim Cook"
        role: "Investor"
        pic: "tim_cook.png"
      attendees:
      - name: "Algolia"
        logo: "algolia.png"
      organizers:
      - name: "STEFANO BERNARDI"
        role: "Investor"
        pic: "bernardi.png"
      - name: "LORENZO SANNA"
        role: "Mountaineer"
        pic: "sanna.png"
      schedule:
      - day: "THURSDAY, SEPT 14"
        program:
        - time: "8.00 AM"
          what: "Breakfast"
          description: "Meet in the Hotel lobby and load up on energies for the day."
        - time: "9.30 AM"
          what: "Cable car for Seiser Alm"
          description: "It's just a short walk to the cable car that will bring us to the
            meadow."
        - time: "10.00 AM"
          what: "Hike to the Refuge"
          description: "It's a 2.5-3h walk to the refuge. But it's a beautiful one."